version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    expose:
      - 27017

  api-docs:
    build:
      context: .
      dockerfile: ./api-docs/Dockerfile
    expose:
      - 3001

  message-broker:
    build:
      context: .
      dockerfile: ./message-broker/Dockerfile
    expose:
      - 7500
      - 3003

  ui-service:
    build:
      context: .
      dockerfile: ./ui-service/Dockerfile
    expose:
      - 3002
    depends_on:
      - mongo
      - message-broker
      - guardian-service

  guardian-service:
    build:
      context: .
      dockerfile: ./guardian-service/Dockerfile
    depends_on:
      - mongo
      - message-broker

  ipfs-client:
    build:
      context: .
      dockerfile: ./ipfs-client/Dockerfile
    ports:
      - 5001:5001
      - 5002:5002
      - 4001:4001
      - 4002:4002
    depends_on:
      - message-broker

  mrv-sender:
    build:
      context: .
      dockerfile: ./mrv-sender/Dockerfile
    expose:
      - 3005

  web-proxy:
    build:
      context: .
      dockerfile: ./web-proxy/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - ui-service
      - api-docs
      - mrv-sender
volumes:
  mongo:
  # volume-guardian-service:
  # volume-ui-service:
  # volume-mrv-sender:
#  volume-message-broker:
