name: Guardian CI
on: [push]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, build, test
        run: |
          pushd interfaces
          npm install
          npm run build
          popd
          pushd vc-modules
          npm install
          npm run build
          npm run test
          pupd
          pushd frontend
          npm install
          npm run build
          npm run test
          popd
          pushd guardian-service
          npm install
          npm run build
          npm run test
          popd
          pushd message-broker
          npm install
          npm run build
          popd
          pushd ui-service
          npm install
          npm run build
          npm run test
          popd
        env:
          CI: true
