name: Guardian CI
on: [push]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, build, test
        run: |
          cd interfaces
          npm install
          npm run build
          cd vc-modules
          npm install
          npm run build
        env:
          CI: true
