name: Publish Images
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/101730247931/locations/global/workloadIdentityPools/hedera-registry-pool/providers/hedera-registry-gh-actions'
          service_account: 'guardian-publisher@hedera-registry.iam.gserviceaccount.com'
